name: CI with Python Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prime-cache-5b3bc7e
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-5b3bc7e
          restore-keys: |
            cache-5b3bc7e

      - name: Show cache hit/miss
        run: echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No requirements file"
